### ISSUE TITLE
How to access the client app

### ISSUE THREAD

**Issue by MeirP-3** [waleedahmad/node-stream#1]
Hello,

I run the project on windows 7. npm start and npm run watch were successful. When I enter "localhost:8888" in chrome, it shows a message saying that adobe flash player must be installed. I installed it but I had a whole different screen than the picture in the tutorial.

Thanks a lot.

**Comment by waleedahmad** [comment]
You can access it at 3333. You can also change it in the config file. 
```
#  /server/config/default.js
const config = {
    server: {
        secret: 'kjVkuti2xAyF3JGCzSZTk0YWM5JhI9mgQW4rytXc',
        port : 3333
    },
    ....
};
```
8888 is node media server's API port.
