### ISSUE TITLE
Login and registration not working 

### ISSUE THREAD

**Issue by DepokSarkar** [waleedahmad/node-stream#11]
When i'm trying to register an account by http://127.0.0.1:3333/register is not working.

**Comment by fitomx19** [comment]
Try to run mongod

**Comment by waleedahmad** [comment]
Added instructions to install MongoDB in https://github.com/waleedahmad/node-stream/commit/fc30132f773b290da7a9cd3ad469606b94dd14c5. Please reopen this issue if you still face issues with authentication.
