### ISSUE TITLE
Is there a way to stream from the browser?

### ISSUE THREAD

**Issue by RaedsLab** [waleedahmad/node-stream#16]
I'm not sure an issue is the best way to ask this. 

Is there a way to stream the webcam through the browser and not have to use OBS or another tool?

**Comment by vaibhav6388** [comment]
Hello,

Have you achieve this?

**Comment by sachinkammar** [comment]
check these blogs [ https://mux.com/blog/the-state-of-going-live-from-a-browser/](url) and [https://morioh.com/p/76f6ad95bdd2](url)

**Comment by sachinkammar** [comment]
check this blog [ https://mux.com/blog/the-state-of-going-live-from-a-browser/](url)
