### ISSUE TITLE
client is not working

### ISSUE THREAD

**Issue by rkanani108** [waleedahmad/node-stream#29]
when i hit http://localhost:3333/
style-sheet is not loaded 
![image](https://user-images.githubusercontent.com/63996355/88709173-6c135e00-d132-11ea-98bc-c4d353b036b8.png)
![image](https://user-images.githubusercontent.com/63996355/88709242-81888800-d132-11ea-9b03-cb533807d255.png)

After login screen nothing to display.
![image](https://user-images.githubusercontent.com/63996355/88709396-b09ef980-d132-11ea-80d1-9ac3e851b1dd.png)

**Comment by hackrahul001** [comment]
i'm also having same error

**Comment by waleedahmad** [comment]
You need to build frontend code by running.

`$ npm run watch`
