### ISSUE TITLE
rtmp reject while testing through OBS

### ISSUE THREAD

**Issue by sham-hq** [waleedahmad/node-stream#3]
Hi,
I am getting **rtmp reject** when trying to read stream from OBS on my server, do you know any reason behind this. I have searched on net and haven't found this error.
Below is the log output:
```
6/9/2019 12:27:17 12008 [INFO] [rtmp connect] id=UUEPJ201 ip=::ffff:x.x.x.x app=live args={"app":"live","type":"nonprivate","flashVer":"FMLE/3.0 (compatible; FMSc/1.0)","swfUrl":"rtmp://x.x.x.x:1935/live","tcUrl":"rtmp://x.x.x.x:1935/live"}
[NodeEvent on prePublish] id=UUEPJ201 StreamPath=/live/sdfsfasd args={}
6/9/2019 12:27:18 12008 [INFO] [rtmp publish] New stream. id=UUEPJ201 streamPath=/live/sdfsfasd streamId=1
6/9/2019 12:27:18 12008 [INFO] [Transmuxing HLS] /live/sdfsfasd to ./server/media/live/sdfsfasd/index.m3u8
6/9/2019 12:27:18 12008 [INFO] [Transmuxing DASH] /live/sdfsfasd to ./server/media/live/sdfsfasd/index.mpd
6/9/2019 12:27:18 12008 [INFO] [rtmp reject] id=UUEPJ201
```

Thanks

**Comment by waleedahmad** [comment]
You are streaming with an invalid streaming key (`sdfsfasd`). I've programmed it to reject connections if the streaming key doesn't belong to any user.  After signing up, you can get your streaming key by visiting `/settings`. You can check this [demo](https://www.youtube.com/watch?v=qY4XCkTqONw) as well.
