### ISSUE TITLE
[INFO] [rtmp play] Stream not found. In production environment

### ISSUE THREAD

**Issue by nobleson** [waleedahmad/node-stream#41]
I have followed the documentation for this project step by step. I first test on Windows, as my development system and i broadcast my stream from OBS, the thumbnails is created with a broken link thereby making the image not to appear. But that's not withstanding, the stream is able to play back. When i tested it in production using Ubuntu 20 on Vultr,  I was able to stream only with the node media server (http://IP:8080/admin/stream) where it plays http-flv but on the web application (http://IP:3333), even the thumbnail could not be created and the logs shows:) **[INFO] [rtmp play] Stream not found.**  Can someone tell me what could possibly be the cause of this?

Thanks

**Comment by patiljignesh** [comment]
Hi @nobleson did you managed to resolve this by any chance?

**Comment by nobleson** [comment]
Yes,
Thanks for your concern.

**Comment by patiljignesh** [comment]
I am receiving the error, do you recall the issue? and how you might have resolved it? Thank you for responding.

**Comment by nobleson** [comment]
Basically it was a poor network from my end. I needed a streaming quality internet service.
